apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  5000: "app/nginx-svc:5000"
  7000: "app/nginx2-svc:7000"
  8000: "app/pgadmin-svc:8000"
  8080: "default/web:8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  namespace: ingress-nginx
data:
  53: "kube-system/kube-dns:53"