apiVersion: v1
kind: ServiceAccount
metadata:
  name: haproxy
  namespace: service
  labels:
    app.kubernetes.io/instance: haproxy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/version: 2.5.0
    helm.sh/chart: haproxy-1.9.0


