---
# Source: postgresql-ha/templates/postgresql/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-postgresql-ha-postgresql
  labels:
    app.kubernetes.io/name: postgresql-ha
    helm.sh/chart: postgresql-ha-8.2.4
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  postgresql-password: "OTByMU5UZ0lFUw=="
  repmgr-password: "NjhGNnBKSlNEVw=="
