apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy
  namespace: service
  labels:
    app.kubernetes.io/instance: haproxy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/version: 2.5.0
    helm.sh/chart: haproxy-1.9.0
data:
  haproxy.cfg: |

    global
      log stdout format raw local0
      maxconn 1024

    defaults
      log global
      timeout client 60s
      timeout connect 60s
      timeout server 60s

    # frontend fe_main
    #   bind :80
    #   default_backend be_main

    # backend be_main
    #   server web1 10.0.0.1:8080 check

    listen nginx
      bind 0.0.0.0:5000
      #acl src1 src 192.168.65.3/32
      #tcp-request connection reject if !src1
      mode tcp
      balance roundrobin
      server s1 nginx-svc.app

    listen nginx2
      bind 0.0.0.0:7000
      # acl src1 src 111.252.110.19/32
      # tcp-request content accept if src1
      # tcp-request content reject
      mode tcp
      balance roundrobin
      server s1 nginx2-svc.app
    
    listen pgadmin
      bind 0.0.0.0:8000
      mode tcp
      balance roundrobin
      server s1 pgadmin-svc.app
    
    listen web
      bind 0.0.0.0:8080
      mode tcp
      balance roundrobin
      server s1 web.default