apiVersion: v1
kind: Service
metadata:
  name: haproxy-svc
  namespace: service
  labels:
    app.kubernetes.io/instance: haproxy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/version: 2.5.0
    helm.sh/chart: haproxy-1.9.0
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
    - name: stat
      protocol: TCP
      port: 1024
      targetPort: stat
    - name: nginx
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: nginx2
      protocol: TCP
      port: 7000
      targetPort: 7000
    - name: pgadmin
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: haproxy
    app.kubernetes.io/name: haproxy
  type: LoadBalancer
