apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.16.1
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/managed-by: Helm
  namespace: postgres
spec:
  type: ClusterIP
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgres
    role: primary
